apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

namespace: portfolio

images:
- name: portfolio
  newName: alxdev52/portfolio
  newTag: 1.0.1-SNAPSHOT
