name: CD
on: 
  push: 
    branches: [main]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build image and push to docker hub
        uses: docker/build-push-action@v1.1.0
        with:
          username: alxdev52
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: alxdev52/portfolio
          tags: ${{ github.sha }}, latest
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize_version: v3.6.1
        
      - name: update k8s
        run: |
          kustomize edit set image portfolio=alxdev52/portfolio:${{ github.sha }}
          cat kustomization.yaml

      - name: commit
        run: |
          git config --global user.email "automation_bot@github.com"
          git config --global user.name "automation bot"
          git commit -am "change image tag"

      - name: push
        uses: ad-m/github-push-action@master